In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import os
import seaborn as sns
import re
import requests
import numpy as np
%matplotlib inline

In [3]:
journals = pd.read_csv(os.getcwd()+'/data/journals.csv')
papers = pd.read_csv(os.getcwd()+'/data/papers/corpus_papers.csv')
affiliations = pd.read_csv(os.getcwd()+'/data/affiliations/affiliations_metadata.csv')
kwords = pd.read_csv(os.getcwd()+'/data/technical_buzzwords.csv')
words = pd.DataFrame(columns = ['topic', 'keywords'])
for i in range(kwords.shape[0]):
    words.loc[len(words.index)] = [kwords.iat[i,0], kwords.iat[i,1].split(", ")]
    
# buzz_counts = pd.read_csv(os.getcwd().replace('scripts', 'data') + '/buzz_counts_by_paper.csv')

buzzwords_in_papers = pd.read_csv(os.getcwd() + '/scripts/found_buzzwords.csv')

# contexts_papers = pd.read_csv(os.getcwd().replace('scripts', 'data') + '/full_text/paper_contexts.csv')

In [14]:
buzzwords_in_papers[buzzwords_in_papers['index'] == 4].groupby('buzz_id').count()

         index  doi  category  subword  count
buzz_id
0            1    1         1        1      1
7            5    5         5        5      5

In [25]:
j = 0
prev = 0
for i in range(buzzwords_in_papers.shape[0]):
    if buzzwords_in_papers.iat[i,0] != prev:
        prev = buzzwords_in_papers.iat[i,0]
        j+=1
    buzzwords_in_papers.iat[i,0] = j

In [23]:
buzzword_encoding.to_csv(os.getcwd()+'/data/buzzword_encoding.csv', index = False)

In [5]:
buzzword_encoding = pd.DataFrame(columns = range(29))

In [18]:
for i in range(len(set(buzzwords_in_papers['index'].tolist()))):
    tmp = buzzwords_in_papers[buzzwords_in_papers['index'] == i]
    
    grouped = tmp.groupby('buzz_id').count()
    
    print(grouped)
    
    app = [0] * 29
    
    for j in grouped.index.tolist():
        app[j] = grouped.loc[j]['index']
        
    buzzword_encoding.loc[len(buzzword_encoding.index)] = app

         index  doi  category  subword  count
buzz_id
7            2    2         2        2      2
         index  doi  category  subword  count
buzz_id
7            2    2         2        2      2
15           1    1         1        1      1
         index  doi  category  subword  count
buzz_id
7            1    1         1        1      1
         index  doi  category  subword  count
buzz_id
7            2    2         2        2      2
19           2    2         2        2      2
         index  doi  category  subword  count
buzz_id
0            1    1         1        1      1
7            5    5         5        5      5
         index  doi  category  subword  count
buzz_id
7            3    3         3        3      3
29           2    2         2        2      2

IndexError: list assignment index out of range

In [19]:
buzzword_encoding

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,2,0,0,...,2,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,5,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,2,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,2,0,0,...,2,0,0,0,0,0,0,0,0,0
9,1,0,0,0,0,0,0,5,0,0,...,0,0,0,0,0,0,0,0,0,0