In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import os
import seaborn as sns
import re
import requests
import numpy as np
%matplotlib inline

In [6]:
journals = pd.read_csv(os.getcwd()+'/data/journals.csv')
papers = pd.read_csv(os.getcwd()+'/data/papers/corpus_papers.csv')
affiliations = pd.read_csv(os.getcwd()+'/data/affiliations/affiliations_metadata.csv')
kwords = pd.read_csv(os.getcwd()+'/data/technical_buzzwords.csv')
words = pd.DataFrame(columns = ['topic', 'keywords'])
for i in range(kwords.shape[0]):
    words.loc[len(words.index)] = [kwords.iat[i,0], kwords.iat[i,1].split(", ")]
    
# buzz_counts = pd.read_csv(os.getcwd().replace('scripts', 'data') + '/buzz_counts_by_paper.csv')

buzzwords_in_papers = pd.read_csv(os.getcwd() + '/scripts/found_buzzwords.csv')

# contexts_papers = pd.read_csv(os.getcwd().replace('scripts', 'data') + '/full_text/paper_contexts.csv')

In [28]:
buzzword_encoding

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,0,0,0,0,0,0,0,33,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,2,0,0,0,0,25,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,4,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,35,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,29,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25848,2,3,0,0,0,0,0,13,0,0,...,0,0,0,0,0,0,0,0,0,0
25849,0,0,0,0,1,0,0,50,0,0,...,0,0,0,0,0,0,0,0,1,4
25850,0,12,0,0,0,0,0,70,0,0,...,0,0,0,1,0,0,0,14,12,3
25851,0,30,4,0,0,0,0,77,0,0,...,0,0,0,0,0,0,0,28,27,8
25852,9152,3705,6610,1650,2136,2156,2575,17674,305,1211,...,5525,564,3081,8065,880,1,83,565,2122,11089

In [25]:
j = 0
prev = 0
for i in range(buzzwords_in_papers.shape[0]):
    if buzzwords_in_papers.iat[i,0] != prev:
        prev = buzzwords_in_papers.iat[i,0]
        j+=1
    buzzwords_in_papers.iat[i,0] = j

In [23]:
buzzword_encoding.to_csv(os.getcwd()+'/data/buzzword_encoding.csv', index = False)

In [18]:

total =[0]*30
for i in range(30):
    total[i] = buzzword_encoding[i].astype(bool).sum(axis=0)

In [20]:
buzzword_encoding.loc[25852] = total

In [19]:
total

[9152,
 3705,
 6610,
 1650,
 2136,
 2156,
 2575,
 17674,
 305,
 1211,
 2156,
 1402,
 200,
 6013,
 3089,
 2010,
 96,
 288,
 12,
 9275,
 5525,
 564,
 3081,
 8065,
 880,
 1,
 83,
 565,
 2122,
 11089]