In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
import os
import seaborn as sns
import re
import requests
import numpy as np
%matplotlib inline

In [48]:
found_bw = pd.read_csv(os.getcwd() + '/found_buzzwords_final.csv')
buzz_encoding = pd.read_csv(os.getcwd().replace('scripts', 'data') + '/buzzword_encoding_step2.csv')
kwords = pd.read_csv(os.getcwd().replace('scripts', 'data')+'/technical_buzzwords.csv')
words = pd.DataFrame(columns = ['topic', 'keywords'])
for i in range(kwords.shape[0]):
    words.loc[len(words.index)] = [kwords.iat[i,0], kwords.iat[i,1].split(", ")]

In [39]:
papers = pd.read_csv(os.getcwd().replace('scripts', 'data') + '/papers/final_valid_papers.csv')

In [50]:
buzz_encoding = buzz_encoding.drop('7', axis = 1)

In [49]:
buzz_encoding

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,19,20,21,22,23,24,25,26,27,28
0,0,0,0,0,0,0,0,0,25,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,22,0,...,0,0,0,0,0,0,0,0,0,0
2,3,0,0,0,0,0,0,0,26,0,...,0,0,0,0,0,0,0,0,0,0
3,4,1,0,0,0,0,0,0,26,0,...,0,0,0,0,0,0,0,0,0,0
4,5,0,0,0,0,0,0,0,47,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21270,26469,5,0,0,0,0,0,0,31,0,...,0,0,0,5,0,0,0,0,0,1
21271,26470,2,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
21272,26471,0,0,0,0,0,3,0,18,0,...,3,0,0,0,0,0,0,0,0,11
21273,26472,0,0,0,0,0,0,0,30,0,...,0,0,0,0,0,0,0,0,0,0
21274,26473,0,0,0,0,0,0,0,81,0,...,0,0,0,0,0,0,0,0,0,3

In [51]:
rows = buzz_encoding.index.tolist()
for r in rows:
    it = [j for j in range(28)]
    it.pop(7)
    cnt = 0
    for i in it:
        if buzz_encoding.loc[r][i]>5:
            cnt +=1
    if cnt <= 1:
        buzz_encoding =buzz_encoding.drop(r)

In [52]:
buzz_encoding

,Unnamed: 0,0,1,2,3,4,5,6,8,9,...,19,20,21,22,23,24,25,26,27,28
6,7,48,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
10,11,19,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
17,19,62,3,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
21,24,31,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
23,26,6,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21259,26458,8,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
21261,26460,25,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21264,26463,3,2,0,0,0,20,0,0,0,...,14,0,0,0,0,0,0,0,0,1
21265,26464,13,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21267,26466,29,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [53]:
cols = words['topic'].tolist()
cols.pop(7)
buzz_encoding.columns = ['index'] + cols

In [42]:
papers

,journal_id,volume_id,year,link,doi,date,pii,eid,scopus_id,citations,authors,affiliations,open_access
0,1,0,2023,https://www.sciencedirect.com/science/article/...,10.1016/j.advwatres.2023.104474,2023-08-01,S0309170823001094,2-s2.0-85161258968,8.516126e+10,0.0,"58307014400, 36008901600, 26635952600",60031268:60031268:60007989,True
1,1,0,2023,https://www.sciencedirect.com/science/article/...,10.1016/j.advwatres.2023.104475,2023-08-01,S0309170823001100,2-s2.0-85161636300,8.516164e+10,0.0,"53984251100, 35610240400","60104134:60104134, 60022461",True
2,1,0,2023,https://www.sciencedirect.com/science/article/...,10.1016/j.advwatres.2023.104476,2023-08-01,S0309170823001112,2-s2.0-85161667219,8.516167e+10,0.0,25822520800,60025063,True
3,1,0,2023,https://www.sciencedirect.com/science/article/...,10.1016/j.advwatres.2023.104477,2023-08-01,S0309170823001124,2-s2.0-85161661769,8.516166e+10,0.0,"57210424267, 36160282300, 7404296426",60018394:60018394:60018394,True
4,1,0,2023,https://www.sciencedirect.com/science/article/...,10.1016/j.advwatres.2023.104485,2023-08-01,S0309170823001203,2-s2.0-85161678744,8.516168e+10,0.0,"56708113100, 7202660185",60030447:60007566,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
26469,28,68,2018,https://www.sciencedirect.com/science/article/...,10.1016/j.envsoft.2017.09.020,2018-01-01,S1364815217304140,2-s2.0-85032268729,8.503227e+10,142.0,"34571084000, 55188785600, 33767605600, 5721638...","60016437:60012197:60012197:60012197, 60025278:...",True
26470,28,68,2018,https://www.sciencedirect.com/science/article/...,10.1016/j.envsoft.2017.09.010,2018-01-01,S1364815216304005,2-s2.0-85032353211,8.503235e+10,54.0,"37111876100, 15069126500, 57189996027, 3574567...","60013141:60025182:60025182:60025182:60013141, ...",True
26471,28,68,2018,https://www.sciencedirect.com/science/article/...,10.1016/j.envsoft.2017.08.002,2018-01-01,S1364815216309550,2-s2.0-85032684995,8.503268e+10,5.0,"7006615627, 49661600900, 15132591800, 66033150...","60021439:60030486, 109682148:60021439:60021439...",True
26472,28,68,2018,https://www.sciencedirect.com/science/article/...,10.1016/j.envsoft.2017.09.011,2018-01-01,S136481521630843X,2-s2.0-85032736133,8.503274e+10,45.0,"56111768300, 37010006200, 43361846100, 5611302...",60068861:60020071:60068861:60024695:60102538:6...,True
26473,28,68,2018,https://www.sciencedirect.com/science/article/...,10.1016/j.envsoft.2017.09.002,2018-01-01,S136481521630648X,2-s2.0-85034039255,8.503404e+10,34.0,"52365181700, 22957372900, 7005864023, 89834056...","60032619, 60032619, 60032619:119771478:6003331...",True

In [67]:
buzz_encoding['doi'] = papers.loc[buzz_encoding['index'].tolist()]['doi'].tolist()

In [66]:
papers.loc[buzz_encoding['index'].tolist()]['doi']

7        10.1016/j.advwatres.2023.104486
11       10.1016/j.advwatres.2023.104493
19       10.1016/j.advwatres.2023.104463
24       10.1016/j.advwatres.2023.104442
26       10.1016/j.advwatres.2023.104460
                      ...
26458      10.1016/j.envsoft.2017.11.010
26460      10.1016/j.envsoft.2017.11.031
26463      10.1016/j.envsoft.2017.11.027
26464      10.1016/j.envsoft.2017.11.002
26466      10.1016/j.envsoft.2017.09.014
Name: doi, Length: 6972, dtype: object

In [25]:
words

,topic,keywords
0,AI and Machine Learning,"[Artificial Intelligence, Machine Learning, Su..."
1,Big Data,"[Hadoop, NoSQL, Apache Flink, Apache Kafka, Bi..."
2,Blockchain and Cryptocurrency,"[Blockchain, Cryptocurrency, Bitcoin, Ethereum..."
3,IoT,"[Smart Medical Device, Industrial IoT, Home Au..."
4,AR and VR,"[Augmented Reality, Virtual Reality, Mixed Rea..."
5,Cybersecurity,"[Cybersecurity, SQL Injection, Ethical Hacking..."
6,Automation,"[Automation, Industrial Automation, Home Autom..."
7,Modeling,"[ArcGIS, HEC-RAS, MIKE, FLOW-2D, QGIS, Telemac..."
8,NLP,"[NLP, Natural Language Processing, Sentiment A..."
9,Quantum Computing,"[Quantum Computing, Quantum Algorithm, Quantum..."
10,5G,"[Massive MIMO, Beamforming, Network Slicing, N..."
11,Edge Computing,"[Edge Computing, Fog Computing, Mobile Edge Co..."
12,Data Analytics,"[Data Analytics, Data Analysis, Business Intel..."
13,Biotechnology,"[Biotechnology, Genetic Engineering, Bioinform..."
14,Nanotechnology,"[Nanotechnology, Graphene Research, Quantum Do..."
15,Wearable Technology,"[Wearable Technology, Fitness Tracker, Smartwa..."
16,Voice User Interface (VUI),"[Voice User Interface, VUI, Amazon Alexa, Goog..."
17,FinTech,"[FinTech, Mobile Payments, Cryptocurrency, Rob..."
18,Data Mining,"[Data Mining, Association Rule Learning, Clust..."
19,Predictive Analysis,"[Predictive Analysis, Fraud Detection, Risk As..."
20,Chatbots,"[Chatbots, Customer Service Bots, Virtual Heal..."
21,3D Printing,"[3D Printing, 3-D Printing Additive Manufactur..."
22,Smart Cities,"[Smart Cities, Smart City, Intelligent Traffic..."
23,Regtech,"[Regtech, Regulatory Technology, Regulatory Fr..."
24,Insurtech,"[Insurtech, Peer-To-Peer Insurance, On-Demand ..."
25,E-Commerce,"[E-Commerce, Mobile Commerce, Social Commerce,..."
26,Serverless Computing,"[Serverless Computing, AWS Lambda, Google Clou..."
27,Software/Platform/Infrastructure as a Service/...,"[Software as a Service, Platform as a Service,..."
28,Web Applications,"[Web Application, Front-end, Back-end, Client-..."

In [31]:
buzz_encoding = buzz_encoding.drop('7', axis = 1)

In [68]:
buzz_encoding

,index,AI and Machine Learning,Big Data,Blockchain and Cryptocurrency,IoT,AR and VR,Cybersecurity,Automation,NLP,Quantum Computing,...,Chatbots,3D Printing,Smart Cities,Regtech,Insurtech,E-Commerce,Serverless Computing,Software/Platform/Infrastructure as a Service/Cloud Computing,Web Applications,doi
6,7,48,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,10.1016/j.advwatres.2023.104486
10,11,19,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10.1016/j.advwatres.2023.104493
17,19,62,3,0,0,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,10.1016/j.advwatres.2023.104463
21,24,31,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,10.1016/j.advwatres.2023.104442
23,26,6,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,10.1016/j.advwatres.2023.104460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21259,26458,8,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,10.1016/j.envsoft.2017.11.010
21261,26460,25,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10.1016/j.envsoft.2017.11.031
21264,26463,3,2,0,0,0,20,0,0,0,...,0,0,0,0,0,0,0,0,1,10.1016/j.envsoft.2017.11.027
21265,26464,13,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10.1016/j.envsoft.2017.11.002
21267,26466,29,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,10.1016/j.envsoft.2017.09.014

In [57]:
papers.loc[26466]

journal_id                                                     28
volume_id                                                      68
year                                                         2018
link            https://www.sciencedirect.com/science/article/...
doi                                 10.1016/j.envsoft.2017.09.014
date                                                   2018-01-01
pii                                             S136481521630487X
eid                                            2-s2.0-85035037271
scopus_id                                           85035037271.0
citations                                                    12.0
authors         36680040200, 7004177153, 57197811867, 66032387...
affiliations    60072651:60072651:60072651:60072651:60026851, ...
open_access                                                  True
Name: 26466, dtype: object

In [69]:
buzz_encoding.to_csv(os.getcwd() + "/tmp.csv", index = False)

In [75]:
buzz_encoding_1t = pd.read_csv(os.getcwd().replace('scripts', 'data') + '/buzzword_encoding_step2.csv').drop('7', axis = 1)

In [76]:
rows = buzz_encoding_1t.index.tolist()
for r in rows:
    it = [j for j in range(28)]
    it.pop(7)
    cnt = 0
    for i in it:
        if buzz_encoding_1t.loc[r][i]>15:
            cnt +=1
    if not cnt == 1:
        buzz_encoding_1t =buzz_encoding_1t.drop(r)

In [77]:
buzz_encoding_1t

,Unnamed: 0,0,1,2,3,4,5,6,8,9,...,19,20,21,22,23,24,25,26,27,28
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,48,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
10,11,19,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
15,17,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16,18,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21270,26469,5,0,0,0,0,0,0,0,0,...,0,0,0,5,0,0,0,0,0,1
21271,26470,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21272,26471,0,0,0,0,0,3,0,0,0,...,3,0,0,0,0,0,0,0,0,11
21273,26472,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21274,26473,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3